services:
  mongo:
    image: mongo:7.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: personal-finance-db
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mysecret
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db
